/* Generated by Yosys 0.9 (git sha1 1979e0b1, i686-w64-mingw32.static-g++ 5.5.0 -Os) */

(* top =  1  *)
(* src = "mux_memoria_estructural_conductual.v:3" *)
module mux_memoria_estructural(clk, reset_L, selector, data_in0, data_in1, data_out);
  (* src = "mux_memoria_estructural_conductual.v:25" *)
  wire [1:0] _0_;
  (* src = "mux_memoria_estructural_conductual.v:4" *)
  input clk;
  (* src = "mux_memoria_estructural_conductual.v:7" *)
  input [1:0] data_in0;
  (* src = "mux_memoria_estructural_conductual.v:8" *)
  input [1:0] data_in1;
  (* src = "mux_memoria_estructural_conductual.v:9" *)
  output [1:0] data_out;
  reg [1:0] data_out;
  (* src = "mux_memoria_estructural_conductual.v:5" *)
  input reset_L;
  (* src = "mux_memoria_estructural_conductual.v:6" *)
  input selector;
  (* src = "mux_memoria_estructural_conductual.v:12" *)
  wire [1:0] temporal_output;
  assign _0_[0] = reset_L ? (* src = "mux_memoria_estructural_conductual.v:26" *) temporal_output[0] : 1'h0;
  assign _0_[1] = reset_L ? (* src = "mux_memoria_estructural_conductual.v:26" *) temporal_output[1] : 1'h0;
  assign temporal_output[0] = selector ? (* src = "mux_memoria_estructural_conductual.v:16" *) data_in1[0] : data_in0[0];
  assign temporal_output[1] = selector ? (* src = "mux_memoria_estructural_conductual.v:16" *) data_in1[1] : data_in0[1];
  (* src = "mux_memoria_estructural_conductual.v:25" *)
  always @(posedge clk)
      data_out[0] <= _0_[0];
  (* src = "mux_memoria_estructural_conductual.v:25" *)
  always @(posedge clk)
      data_out[1] <= _0_[1];
endmodule
